CFLAGS=-g
OBJ=Opening.o Option.o Story.o Ship.o Small.o Middle.o Large.o Patrol.o Mother.o Approach.o Longdistance.o TimeList.o Ccurses.o Allmessage.o Enermy.o Player.o main.o timer.o ShipList.o AttackLine.o SelectUnite.o Bridge.o
Galaxy_Hero_Legend: $(OBJ)
	g++ -o Galaxy_Hero_Legend $(CFLAGS) $(OBJ) -lcurses
main.o: main.c
	g++ -c $(CFLAGS) main.c
Ship.o: Ship.c
	g++ -c $(CFLAGS) Ship.c
Small.o: Small.c
	g++ -c $(CFLAGS) Small.c
Middle.o: Middle.c
	g++ -c $(CFLAGS) Middle.c
Large.o: Large.c
	g++ -c $(CFLAGS) Large.c
Patrol.o: Patrol.c
	g++ -c $(CFLAGS) Patrol.c
Mother.o: Mother.c
	g++ -c $(CFLAGS) Mother.c
Approach.o: Approach.c
	g++ -c $(CFLAGS) Approach.c
Longdistance.o: Longdistance.c
	g++ -c $(CFLAGS) Longdistance.c
TimeList.o: TimeList.c
	g++ -c $(CFLAGS) TimeList.c
Enermy.o: Enermy.c
	g++ -c $(CFLAGS) Enermy.c
Player.o: Player.c
	g++ -c $(CFLAGS) Player.c
Ccurses.o: Ccurses.c
	g++ -c $(CFLAGS) Ccurses.c
Allmessage.o: Allmessage.c
	g++ -c $(CFLAGS) Allmessage.c
Opening.o: Opening.c
	g++ -c $(CFLAGS) Opening.c
Option.o: Option.c
	g++ -c $(CFLAGS) Option.c
Story.o: Story.c
	g++ -c $(CFLAGS) Story.c
timer.o: timer.c
	g++ -c $(CFLAGS) timer.c
ShipList.o: ShipList.c
	g++ -c $(CFLAGS) ShipList.c
AttackLine.o: AttackLine.c
	g++ -c $(CFLAGS) AttackLine.c
SelectUnite.o: SelectUnite.c
	g++ -c $(CFLAGS) SelectUnite.c
Bridge.o: Bridge.c
	g++ -c $(CFLAGS) Bridge.c
clean:
	rm *.o
	rm Galaxy_Hero_Legend
